### ISSUE TITLE
Build & Design Observation Webpage

### ISSUE THREAD

**Issue by TekuConcept** [USU-Robosub/Poseidon#11]
One tab per feature:
- Motor Control & Status
- Visuospatial 3D Map, Navigation, Basic Sensor Readings
- Hull Integrity & Detailed Sensor Readings

**Comment by Jesse-V** [comment]
I have initial remote control for this, so this is now started. See the Client folder in the client-server branch.

**Comment by Jesse-V** [comment]
After yesterday's success, I'm going to consider this closed, but it's still an item will will continue to work on.
