### ISSUE TITLE
Complete Sensors

### ISSUE THREAD

**Issue by kburgon** [USU-Robosub/Poseidon#111]
### Requirements to have the sensors complete and ready to be used in the brain:

- [ ] Complete code for external sensors (this includes adding write capabilities to the serial class
- [ ] Find source of heisenbug and resolve it
- [ ] Interpret log data and use sensors to complete a task

**Comment by madfrog54321** [comment]
Replaced by [issue #173](https://github.com/USU-Robosub/Poseidon/issues/173).
