### ISSUE TITLE
Arduino Reads Garbage On Initial Startup

### ISSUE THREAD

**Issue by TekuConcept** [USU-Robosub/Poseidon#132]
## Summary

When the Arduino's Serial is connected to for the first time, garbage data is given via `Serial.read()`.
What I discovered is that most times, the 'value' of the garbage is consistent but the amount of garbage is random. The value of the garbage is unique to both the baud rate and the Arduino device. For the Arduino Due with a baud of 115200, the garbage value is '0'.

Note: `Arduino.available()` will not resolve this issue.
## Acceptance Criteria

When the Arduino is initialized, it
- [ ] cycles through the input buffer until the buffer is clear
- [ ] sends a response of `"ready"` to the BeagleBone
- [ ] catches any exceptions and returns "`failure`" to the BeagleBone
## Non-functional Criteria

The `"ready"` response is valid JSON. An extra JSON library doesn't needed to be added to finish this issue.

**Comment by TekuConcept** [comment]
Discussing this with @kburgon, sending the char "r" or "R" would be easier to manage instead of the full string "ready".

**Comment by nfcopier** [comment]
Of course, complete words are better when possible. But this is one place where it makes sense to abbreviate. Sounds like a good idea to me.
