### ISSUE TITLE
Temperature JavaScript Module

### ISSUE THREAD

**Issue by nfcopier** [USU-Robosub/Poseidon#140]
## Summary

Two modules should be added to get temperature data: one that uses the driver from #137 and gets internal temperature and one that uses the module from #133 and gets the external temperature. It would be ideal if these two modules share the same interface.

## Non-functional Criteria

**Comment by madfrog54321** [comment]
Replaced by [issue #173](https://github.com/USU-Robosub/Poseidon/issues/173).
