### ISSUE TITLE
DVL Headers

### ISSUE THREAD

**Issue by nfcopier** [USU-Robosub/Poseidon#144]
## Summary

The header files for the DVL should be located or reverse-engineered. Some useful documentation should be created.

**Comment by TekuConcept** [comment]
Just to clarify: You will need to write your own software drivers for the Teledyne Doppler Velocity Log.
There are no pre-existing drivers or linux-based software of any kind provided by Teledyne according to their website: rdinstruments.com

They, however, do provide a detailed explanation of packet information that is sent and received serially. (You will need to create another tty serial interface to the DVL device.)

**Comment by TekuConcept** [comment]
DVL code has been written for this device in the Drivers Repository. This issue may now be closed.
