### ISSUE TITLE
Upload Video Footage to NAS

### ISSUE THREAD

**Issue by nfcopier** [USU-Robosub/Poseidon#164]
## Summary

Our video footage is scattered about various devices. This footage should all be located and uploaded to the NAS. This is blocking #149.

## Acceptance Criteria

- [ ] Both GoPros have had their footage uploaded to the NAS
- [ ] Both All-In-One computers should be checked for footage and have that uploaded to the NAS
- [ ] Directories on the NAS should be well organized and named so that the footage can easily be located

**Comment by nfcopier** [comment]
@TekuConcept, has this been done? Can I close this issue?

**Comment by TekuConcept** [comment]
Yes - not all of it but most definitely the one that contains all footage one could possibly need. (Including some buoy footage)

**Comment by TekuConcept** [comment]
Content can be found on our NAS under
> - "/Downloads/Video/GoPro June Pool Time"
> - "/Downloads/Video/2016 Competition"
