### ISSUE TITLE
Adding quaternion support to node.js

### ISSUE THREAD

**Issue by madfrog54321** [USU-Robosub/Poseidon#172]
## Summary

To define the rotation of the sub in 3d space, quaternions must be used. There is a [quaternion ](https://www.npmjs.com/package/quaternion) library that can be installed using npm. It needs to be added to automated build files for the repository. 
## Acceptance Criteria
- [ ] the quaternion library needs to be added to the repository
## Non-functional Criteria

The library may only need to be installed on the sub, but documentation should be added to the project saying it is being used.

**Comment by nfcopier** [comment]
I like the library you suggested. I might also suggest finding a C++ library. If we _are_ doing some really mathy stuff, we might want to keep it in the C++ module.
