### ISSUE TITLE
Extended math library for C++

### ISSUE THREAD

**Issue by madfrog54321** [USU-Robosub/Poseidon#177]
## Summary

Because sensor fusion can take a large amount of processing power and requires precise timing, the sensor fusion code should be implemented in the C++ module. To allow the development of the simplified sensor interfaces in the C++ module a extended math library needs to be added to the C++ module. 

## Acceptance Criteria

- [x] Choose math library.
- [x] Chosen math library needs to have at least matrix, vector, and quaternion support. 
- [x] The math library has been added to the C++ module in the repository.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/97672069335178/208616366694015)

**Comment by madfrog54321** [comment]
I have found [Eigen](http://eigen.tuxfamily.org/index.php?title=Main_Page) as a possible math library.

**Comment by TekuConcept** [comment]
Depending on your requirements, I could give you all 3 of those classes (already written) - trying to reduce the footprint and dependency requirements.

**Comment by madfrog54321** [comment]
I added all the code for Vector3 and Quaternion in commit [e05f350](https://github.com/USU-Robosub/Poseidon/commit/e05f3504c3389170fddb19ba7506757f5a7b8359).

**Comment by nfcopier** [comment]
Issues should not be closed until the relevant code has been merged into develop.
