### ISSUE TITLE
Implementing IPoseProvider in C++

### ISSUE THREAD

**Issue by madfrog54321** [USU-Robosub/Poseidon#178]
## Summary

To provide the brain with the position and orientation of the sub, a pose provider is needed. To allow  expansion of the sensor fusion algorithm, a IPoseProvider class needs to be created. At a later time a full sensor fusion or map algorithm will be implemented.

## Acceptance Criteria

When [external actor] does [action], [module]
- [x] When getPosition is called it should return a Vector3 of the sub's offset from its start location. 
- [x] When getOrientation is called it should return a Quaternion of the sub's offset from level and start direction.

## Non-functional Criteria

- [x] The pose provider should be used by the sub's command dispatcher and assembler.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/97672069335178/214247456460826)

**Comment by madfrog54321** [comment]
IPoseProvider has been implemented in commit [e05f350](https://github.com/USU-Robosub/Poseidon/commit/e05f3504c3389170fddb19ba7506757f5a7b8359)

**Comment by nfcopier** [comment]
Issues should not be closed until the relevant fix is on develop.
