### ISSUE TITLE
Remote control server doesn't close connections properly

### ISSUE THREAD

**Issue by Jesse-V** [USU-Robosub/Poseidon#18]
TCP connections can sometimes get left open if the server is killed, so the port will be stuck in the TIME_WAIT state. This prevents the server from correctly listening on that port again.

**Comment by Jesse-V** [comment]
Adding tear-down into the constructor might be a viable solution to this issue.

**Comment by Jesse-V** [comment]
I got around this by having it wait and handle reads on a thread, rather than locking waiting for a read.

**Comment by nfcopier** [comment]
Having switched to Node.js and JavaScript, we'll likely use a standard web application and client. Closing this as irrelevant.
