### ISSUE TITLE
Create TelemetryPacket object

### ISSUE THREAD

**Issue by nfcopier** [USU-Robosub/Poseidon#180]
## Summary

The `TelemetryPacket` object will contain all the information generated by the SLAM module. It will contain the camera frame, depth map, pose, and time stamp.

## Acceptance Criteria

- [ ] There is some way to create a `TelemetryPacket`
- [ ] When `GetCameraFrame()` is called an OpenCV image object is returned.
- [ ] When `GetDepthMap()` is called a `DepthMap` object is returned.
- [ ] When `GetPose()` is called a `Pose` object is returned.
- [ ] When `GetTimeStamp()` is called a Chrono object is returned.

**Comment by Kjens93** [comment]
Looks like there is an `IPoseProvider` interface somewhere that will provide details as to the required implementation. See #183.

**Comment by Kjens93** [comment]
Still not sure if we are returning the depth map or if it will be created by the Particle Filter module. See #187.

**Comment by nfcopier** [comment]
You will use the Depth Map. But it will be created by the SLAM team.

**Comment by Kjens93** [comment]
Implemented as a `struct`. See #197.
