### ISSUE TITLE
Create Particle Filter Dependency Functions

### ISSUE THREAD

**Issue by TekuConcept** [USU-Robosub/Poseidon#188]
These functions will be used as part of the calculating process of the particle filter algorithm.

- [x] Normal Distribution Function: accepts the error (sigma), the feature's distance (D), and the tested distance (d), and returns a normal distributed value between 0 and 1. Tested distances further from the feature's distance should return values closer to 0. Tested distances closer to the feature's distance should return values closer to 1 (or the max peak value). 

See also:
- [Normal (Gaussian) Distribution - Wikipedia](https://en.wikipedia.org/wiki/Normal_distribution)
- [Normal (Gaussian) Distribution - Wolfram](http://mathworld.wolfram.com/NormalDistribution.html)

- [x] Blend Function 1: accepts a standard deviation, and a percent good, and blends them into a meaningful value between 0 and 1. Standard deviation and percent good will each have values ranging between 0 and 1.

See also:
- [Conditional Probability](https://en.wikipedia.org/wiki/Conditional_probability)

**Comment by nfcopier** [comment]
@madfrog54321 was adding some kind of math library to the project. You might want to ask him about it and see whether it has a normal distribution already.
