### ISSUE TITLE
Create structure for depth map

### ISSUE THREAD

**Issue by madfrog54321** [USU-Robosub/Poseidon#193]
## Summary

`DepthMap` will store how far each pixel is from the camera.

## Acceptance Criteria

- [x] The `DepthMap` object can be instantiated given `(width, height)`
- [x] When `SetDepth(x, y, depth)` is called, the depth of the given pixel is saved [*will be in meters*] . 
- [x] When `GetDepth(x, y)` is called, the depth of the given pixel is returned [*will be in meters*]. 

## Non-functional Criteria

The depth data type does not need to be high precision.

**Comment by aparker10** [comment]
Is the width and height in meters as well?

**Comment by madfrog54321** [comment]
The width and height will be in pixels.

**Comment by madfrog54321** [comment]
Could you add a hard defined value for "unknown depth". Something like `#DEFINE UNKNOWN_DEPTH -1` That way we don't have to remember the actual value for a pixel that does not have a set depth. You could initialize the `DepthMap` object with that value. That way it will have a known starting state.

**Comment by aparker10** [comment]
Okie doke!
