### ISSUE TITLE
Interface Camera to Processing Unit

### ISSUE THREAD

**Issue by TekuConcept** [USU-Robosub/Poseidon#2]
Read in HSYNC buffer from camera and write to processor. VSYNC validates a single frame. (The OV7670 camera defaults to approximately 30FPS at 32kp/frame while the OV5642 defaults to approximately 15FPS at 5mp/frame.)

Create raw YUV image file from buffers.

**Comment by davidrotor** [comment]
Hello Chris, Ive retaken my beaglebone black project since I put it on hold
because of the workload I had in my final year. Can you guide me through
what does the PRU have to do or how do I take pictures with the omnivision
cameras?

**Comment by TekuConcept** [comment]
The objective of the PRU is to read a byte from the camera on the rising edge of the camera's PCLK. It then writes the byte to RAM where your C-program will read that byte. The frame (or picture) is finished writing on the rising edge of VSNC.

Unfortunately I can't explain any further since I do not have a working solution yet - I just got our ALTERA Max II working (required for our stereo vision). I would like to use the GPMC instead of the PRU for a higher throughput (100MHz vs 50MHz).

By the way, if you need something working now, there is always the LogiBone cape, though it may be a little pricy in my opinion. :)

**Comment by TekuConcept** [comment]
(currently irrelevant to this project - maybe can be reopened in a future build)
