### ISSUE TITLE
Set Up Opencv on the BeagleBones

### ISSUE THREAD

**Issue by samachr** [USU-Robosub/Poseidon#20]

**Comment by nfcopier** [comment]
@TekuConcept, I know you've been doing some work on this. Will you close this issue when it's done?

**Comment by TekuConcept** [comment]
Yes, OpenCV has already been compiled on BoneVision. I also have the compressed archive of the compiled project which can easily be uploaded to other bones.

**Comment by nfcopier** [comment]
Well, after a year, I declare this issue resolved! :grin:
