### ISSUE TITLE
CMake server error: "rice/Data_Type.hpp" not found on include in main.cpp

### ISSUE THREAD

**Issue by kburgon** [USU-Robosub/Poseidon#22]
This error is given when trying to compile the server in Poseidon/Server/build.

**Comment by srphillips** [comment]
Fixed CMakeLists.txt on the BeagleBone, but apparently the code on the BBB is not tied to git at all currently so there is no git repo to push to yet. In any event, the Cmake build now works on the BBB itself and I will push changes up here somehow later.
