### ISSUE TITLE
Add IMU Controller

### ISSUE THREAD

**Issue by nfcopier** [USU-Robosub/Poseidon#26]
We need to be able to receive data from the IMU.

- [ ] IMU Controller is initialized with a connection to the Node app.
- [x] IMU Controller receives data from the drivers.
- [ ] Node app has interface to the IMU Controller.

The I feel like the best implementation is to have the Node interface constantly pulling for data and caching the most recent data set.

*A note on acronyms in code: The generally accepted convention for acronyms in code is to capitalize only the first letter, i.e.: `ImuController` vs `IMUController`.

**Comment by TekuConcept** [comment]
IMU is an acronym in and of its self. It stands for Inertial Measurement Unit; Thus I capitalized it as follows: "IMUController" (In addition, it also looks nicer)

**Comment by nfcopier** [comment]
I know it's an acronym. That's why I put that note. I would disagree that `IMUController` looks nicer. I find the lack of clear separation of words makes it difficult to read. This is why most linters discourage that type of capitalization.

**Comment by TekuConcept** [comment]
The IMU driver code that uses I2C needs to be implemented on the Arduino while the serial interface needs to be done on the Bone. The existing functions such as "sealevelPresure" also should be implemented on the Arduino in order to preserve efficiency with data transfers.

**Comment by butterfieldj** [comment]
Yep, I will get to work on this hopefully tomorrow. Is anyone planning on
being in the lab tomorrow? I still don't have a key card.

**Comment by TekuConcept** [comment]
I may be there along with Nathan, and maybe Kevin? Tomorrow we also have the regular Tuesday meeting. (Don't worry about the files: BMP085, HMC5883L, and MPU6050, those are going on the Arduino - I should have them tested by the end of the day)

**Comment by butterfieldj** [comment]
Ok, what time are you going to be there?

**Comment by TekuConcept** [comment]
Maybe before 12pm, but guaranteed after 4:15pm

**Comment by butterfieldj** [comment]
Sounds good, I'll see you guys there.

**Comment by TekuConcept** [comment]
Resolved by #93.
