### ISSUE TITLE
Integrate Thrust and Power Controllers

### ISSUE THREAD

**Issue by nfcopier** [USU-Robosub/Poseidon#28]

**Comment by TekuConcept** [comment]
No, the IMU will still use I2C - because the IMU will still be directly attached to the bone and not the Arduino Due.

Only the thrust controller, power controller and hydrophones will use serial.

**Comment by nfcopier** [comment]
I misunderstood. Rather than close the issue, why didn't you just update the name? Did you create a new issue?
