### ISSUE TITLE
Add Power Controller

### ISSUE THREAD

**Issue by nfcopier** [USU-Robosub/Poseidon#37]
We need a power controller to turn on the ESCs. The ESC driver should implement the IPowerModule interface and live in the Dirvers directory. The power controller should implement the IPowerController interface and live in the Peripherals directory.
- [x] Arduino can toggle ESCs.
- [x] Add Beaglebone driver for ESCs
- [x] Add PowerController
- [x] Add PowerController interface in Node app
- [x] CommandDispatcher dispatches PowerController commmands

**Comment by TekuConcept** [comment]
This issue has been satisfied, correct?

**Comment by nfcopier** [comment]
Yes it has. Thanks for catching this.
