### ISSUE TITLE
Add LightController

### ISSUE THREAD

**Issue by nfcopier** [USU-Robosub/Poseidon#38]
We need a way to turn on/off the lights on the sub. I kinda feel like it makes more sense for the lights to be turned on when the app is started and are left on.

- [x] Define light interfaces
- [x] Arduino can control lights
- [x] Add light controller
- [x] Add light driver
- [x] Lights switched on during bootstrap

**Comment by kburgon** [comment]
All the code for the lights is written up, it just needs to be tested on the arduino and merged in.  I am not checking anything else off until the serial communications  portion is finalized.
