### ISSUE TITLE
"Error: free(): invalid pointer" when calling exit command

### ISSUE THREAD

**Issue by TekuConcept** [USU-Robosub/Poseidon#76]
Here is the specific output in the terminal:

```
info Stopping Thrusters...
*** Error in `./Bootstrap': free(): invalid pointer: 0x0002b280 ***
Aborted
```

**Comment by TekuConcept** [comment]
This bug has been fixed. This issue may be closed.

**Comment by nfcopier** [comment]
Is it fixed on develop or is it part of your pending changes? If the former, go ahead and hit the close button.
