### ISSUE TITLE
Refactor Sockets to Have a Clean Interface

### ISSUE THREAD

**Issue by nfcopier** [USU-Robosub/Poseidon#80]
### Acceptance Criteria
- [x] Third party code is hidden behind Client adapter class
- [x] Client adapter constructor takes a port
- [x] Client adapter extends from `ostream` and implements the insertion operator
- [x] Client adapter extends from `istream` and implements the extraction operator
- [x] Adapter isn't singletons. Many instances can be created each listening on their own port
- [x] Adapter code is clean and readable

I don't think the sockets necessarily need to be implemented. That'd probably be too much change for a single branch.

**Comment by TekuConcept** [comment]
Operator overloading for both istream and ostream function differently compared to the intended operator functionality. For example:

istream overloading
`friend istream &operator>>( istream  &input, std::string &line )
{ 
     input >> line;
     return input;            
}`

desired overloading
`void operator>>(std::string line)
{
     char* buffer;
     socket->recv(buffer, size);
     line = buffer;
}

Also, clients and servers can both send and receive data. It may be more fitting to use both ``<<'' and ``>>'' for each adapter.
