### ISSUE TITLE
Each Controller Gets Its Own Socket

### ISSUE THREAD

**Issue by nfcopier** [USU-Robosub/Poseidon#82]
The Brain should create separate sockets for each of its CppInterface classes. It should pass the ports for these sockets to Peripherals somehow. CommandDispatcher should be extracted into several smaller classes for each of our controllers (or perhaps a single switch function inside each of our controllers). Bootstrap should create a socket with the correct port received from Brain and give each of these sockets to the respective controller. A factory class probably should be used to keep Bootstrap clean.

**Comment by kburgon** [comment]
No longer Relevant
